spring.application.name=spring-ai-rag-server

# ==========================================
# PostgreSQL Database Configuration
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# Spring AI PGVector Configuration
# ==========================================
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=1024

# ==========================================
# Ollama Model Configuration
# ==========================================
spring.ai.ollama.chat.model=llama3
spring.ai.ollama.embedding.model=mxbai-embed-large
